-- MySQL Script generated by MySQL Workbench
-- Fri Jul 31 19:30:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema school-administration-system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `school-administration-system` ;

-- -----------------------------------------------------
-- Schema school-administration-system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `school-administration-system` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
SHOW WARNINGS;
USE `school-administration-system` ;

-- -----------------------------------------------------
-- Table `school-administration-system`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`class` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`class` (
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `school-administration-system`.`class_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`class_subject` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`class_subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `classCode` VARCHAR(45) NULL,
  `subjectCode` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `classCode`
    FOREIGN KEY (`classCode`)
    REFERENCES `school-administration-system`.`class` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `subjectCode`
    FOREIGN KEY (`subjectCode`)
    REFERENCES `school-administration-system`.`subject` (`code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `classCode_UNIQUE` ON `school-administration-system`.`class_subject` (`classCode` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `subjectCode_UNIQUE` ON `school-administration-system`.`class_subject` (`subjectCode` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `id_UNIQUE` ON `school-administration-system`.`class_subject` (`id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `school-administration-system`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`student` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`student` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `school-administration-system`.`student` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `school-administration-system`.`student_class_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`student_class_subject` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`student_class_subject` (
  `email` VARCHAR(45) NOT NULL,
  `class` INT NULL,
  PRIMARY KEY (`email`),
  CONSTRAINT `studentEmail`
    FOREIGN KEY (`email`)
    REFERENCES `school-administration-system`.`student` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `studentClass`
    FOREIGN KEY (`class`)
    REFERENCES `school-administration-system`.`class_subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `school-administration-system`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`subject` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`subject` (
  `code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `school-administration-system`.`subject` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `school-administration-system`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`teacher` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`teacher` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name_UNIQUE` ON `school-administration-system`.`teacher` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `school-administration-system`.`teacher_class_subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `school-administration-system`.`teacher_class_subject` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `school-administration-system`.`teacher_class_subject` (
  `email` VARCHAR(45) NOT NULL,
  `class` INT NOT NULL,
  CONSTRAINT `teacherEmail`
    FOREIGN KEY (`email`)
    REFERENCES `school-administration-system`.`teacher` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teacherClass`
    FOREIGN KEY (`class`)
    REFERENCES `school-administration-system`.`class_subject` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `teacherEmail_UNIQUE` ON `school-administration-system`.`teacher_class_subject` (`email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `classCode_UNIQUE` ON `school-administration-system`.`teacher_class_subject` (`class` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
